name: amls2

dependencies:
  - python=3.9
  - pip=22.1.*
  - pip:
    - opencv-python==4.7.*
    - matplotlib==3.7.*
    - numpy==1.24.*
    - keras>=2.9.*
    - pandas>=1.4.*
    - tensorflow>=2.9.*
    - Pillow>=9.*
    # - "--editable=git+https://github.com/ocampor/image-quality@master#egg=image-quality"
    - piqa>=1.2.*
    - scikit-image>=0.20.*
    - h5py>=3.*
